---
title: "01-data_processing"
output: html_document
date: "2025-01-03"
---

### Load libraries
```{r}
library(tidyverse)
library(readxl)
install.packages("chron")
library(chron)
library(ggplot2)
install.packages("devtools")
library(devtools)
devtools::install_github("psyteachr/introdataviz")
install.packages("introdataviz")
library(introdataviz)
library(splines)
library(mgcv)

```


### Load data
```{r}
uploaded <- read_csv("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/FHL_weather/data/FHL_weather_All_GL.csv")
twentytwo <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/FHL_weather/data/2022.xlsx")
twentythree <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/FHL_weather/data/2023.xlsx")
twentyfour <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/FHL_weather/data/2024.xlsx")
```


### Clean up uploaded dataset
```{r}
uploaded_trim <- subset(uploaded, select = -c(Lat, Lon, Platform_ID, Time_PST, ISO_DateTime_UTC, Date_PST, Rad_tot))
uploaded_trim$ISO_DateTime_PST <- gsub("T", " ", uploaded_trim$ISO_DateTime_PST)
uploaded_trim$ISO_DateTime_PST <- as.POSIXct(uploaded_trim$ISO_DateTime_PST, format = "%Y-%m-%d %H:%M:%OS")
names(uploaded_trim)[names(uploaded_trim) == 'ISO_DateTime_PST'] <- 'Date'


```

### Clean up 2022 dataset
```{r}


twentytwo$Date <- as.POSIXct(twentytwo$Date, format = "%Y%m%d")
twentytwo$Time <- format(as.POSIXlt(twentytwo$Time, format="%H%M%S"),"%H:%M:%S")
twentytwo$Date <- as.POSIXct(paste(twentytwo$Date, twentytwo$Time), format="%Y-%m-%d %H:%M:%S")
twentytwo_clean <- subset(twentytwo, select = -c(Time))

for (i in 1:(length(twentytwo_clean$Date) - 4)) {  # Changed to `-4` so you don't go out of bounds
  # Skip rows where Date is NA
  if (is.na(twentytwo_clean$Date[i]) | is.na(twentytwo_clean$Date[i + 1])) {
    next  # Skip this iteration if there's an NA value
  }
  
  # Check for "23:45:00" and the next datetime being at "00:00:00" and additional conditions
  if ((format(twentytwo_clean$Date[i], "%H:%M:%S") == "23:45:00" && 
       format(twentytwo_clean$Date[i + 1], "%H:%M:%S") == "00:00:00" && 
       format(twentytwo_clean$Date[i + 1], "%m") == "12") ||
      (format(twentytwo_clean$Date[i], "%H:%M:%S") == "23:45:00" && 
       format(twentytwo_clean$Date[i + 1], "%H:%M:%S") == "00:00:00" && 
       format(twentytwo_clean$Date[i + 1], "%m-%d") == "11-30")) {
    # Adjust the date of the next few rows to the current day's date
    twentytwo_clean$Date[i + 1] <- twentytwo_clean$Date[i + 1] + 86400  # Add one day (86400 seconds)
    twentytwo_clean$Date[i + 2] <- twentytwo_clean$Date[i + 2] + 86400
    twentytwo_clean$Date[i + 3] <- twentytwo_clean$Date[i + 3] + 86400
    twentytwo_clean$Date[i + 4] <- twentytwo_clean$Date[i + 4] + 86400  # Add one day (86400 seconds)
  }
}

```

### Clean up annual datasets
```{r}
twentyfour_clean <- subset(twentyfour, select = -c(Time))
twentythree_clean <- subset(twentythree, select = -c(Time))

twentyfour_clean$Year <- format(twentyfour_clean$Date, format="%Y")
twentyfour_clean$Month <- format(twentyfour_clean$Date, format="%m")
twentyfour_clean <- twentyfour_clean %>%
  select(Year, Month, everything())

twentythree_clean$Year <- format(twentythree_clean$Date, format="%Y")
twentythree_clean$Month <- format(twentythree_clean$Date, format="%m")
twentythree_clean <- twentythree_clean %>%
  select(Year, Month, everything())

twentytwo_clean$Year <- format(twentytwo_clean$Date, format="%Y")
twentytwo_clean$Month <- format(twentytwo_clean$Date, format="%m")
twentytwo_clean <- twentytwo_clean %>%
  select(Year, Month, everything())

uploaded_trim$Month <- format(uploaded_trim$Date, format="%m")
uploaded_trim <- uploaded_trim %>%
  select(Year, Month, everything())
```


### Make columns structurally compatible
```{r}
# Convert Year column to character in all dataframes
uploaded_trim$Year <- as.character(uploaded_trim$Year)
twentytwo_clean$Year <- as.character(twentytwo_clean$Year)
twentythree_clean$Year <- as.character(twentythree_clean$Year)
twentyfour_clean$Year <- as.character(twentyfour_clean$Year)
```

```{r}
# Convert Rad_PAR column to numeric (double) in all dataframes
uploaded_trim$Rad_PAR <- as.numeric(uploaded_trim$Rad_PAR)
twentytwo_clean$Rad_PAR <- as.numeric(twentytwo_clean$Rad_PAR)
twentythree_clean$Rad_PAR <- as.numeric(twentythree_clean$Rad_PAR)
twentyfour_clean$Rad_PAR <- as.numeric(twentyfour_clean$Rad_PAR)

```

```{r}
# Convert Rad_Energy column to numeric (double) in all dataframes
uploaded_trim$Rad_Energy <- as.numeric(uploaded_trim$Rad_Energy)
twentytwo_clean$Rad_Energy <- as.numeric(twentytwo_clean$Rad_Energy)
twentythree_clean$Rad_Energy <- as.numeric(twentythree_clean$Rad_Energy)
twentyfour_clean$Rad_Energy <- as.numeric(twentyfour_clean$Rad_Energy)

```

```{r}
# Convert Wind_speed column to numeric (double) in all dataframes
uploaded_trim$Wind_speed <- as.numeric(uploaded_trim$Wind_speed)
twentytwo_clean$Wind_speed <- as.numeric(twentytwo_clean$Wind_speed)
twentythree_clean$Wind_speed <- as.numeric(twentythree_clean$Wind_speed)
twentyfour_clean$Wind_speed <- as.numeric(twentyfour_clean$Wind_speed)

```


```{r}
### Convert wind chill to numeric
uploaded_trim$Wind_Chill <- as.numeric(uploaded_trim$Wind_Chill)
twentytwo_clean$Wind_Chill <- as.numeric(twentytwo_clean$Wind_Chill)
twentythree_clean$Wind_Chill <- as.numeric(twentythree_clean$Wind_Chill)
twentyfour_clean$Wind_Chill <- as.numeric(twentyfour_clean$Wind_Chill)
```

```{r}
### Convert rain to numeric
uploaded_trim$Rain <- as.numeric(uploaded_trim$Rain)
twentytwo_clean$Rain <- as.numeric(twentytwo_clean$Rain)
twentythree_clean$Rain <- as.numeric(twentythree_clean$Rain)
twentyfour_clean$Rain <- as.numeric(twentyfour_clean$Rain)
```

### Combine yearly datasets
```{r}
weather <- bind_rows(uploaded_trim, twentytwo_clean, twentythree_clean, twentyfour_clean)

weather$Month <- format(weather$Date, format="%m")
weather$Year <- format(weather$Date, format="%Y")

weather_clean_unique <- weather[!duplicated(weather$Date), ]
weather_clean_unique <- na.omit(weather_clean_unique)
```

### Graphs
```{r}
ggplot(weather_clean_unique, aes(x=Year, y= Wind_Chill, fill = Year))+
  geom_violin()+
  theme_classic()+
  ylab("Wind Chill (°C)")+
  geom_hline(yintercept = 10)+
  theme(axis.title = element_text(size=20, color = "black"),
        axis.text = element_text(size=18, color = "black"))
  
```


```{r}
ggplot(weather_clean_unique, aes(x=Date, y = Rad_PAR))+
  geom_point()+
  theme_classic()
```

```{r}
ggplot(weather_clean_unique, aes(x=Date, y = Rad_Energy))+
  geom_point()+
  theme_classic()+
  ylim(0,1200)+
  ylab("Radiant Energy")
```

```{r}
weather_clean_unique %>%
  filter(Date >= "2023-07-25 00:00:00" & Date <= "2023-07-25 23:45:00") %>%
ggplot(aes(x=Date, y = Rad_Energy))+
  geom_point()+
  theme_classic()+
  ylim(0,1200)+
  ylab("Radiant Energy")
```



```{r}
GeomSplitViolin <- ggproto("GeomSplitViolin", GeomViolin, 
                           draw_group = function(self, data, ..., draw_quantiles = NULL) {
  data <- transform(data, xminv = x - violinwidth * (x - xmin), xmaxv = x + violinwidth * (xmax - x))
  grp <- data[1, "group"]
  newdata <- plyr::arrange(transform(data, x = if (grp %% 2 == 1) xminv else xmaxv), if (grp %% 2 == 1) y else -y)
  newdata <- rbind(newdata[1, ], newdata, newdata[nrow(newdata), ], newdata[1, ])
  newdata[c(1, nrow(newdata) - 1, nrow(newdata)), "x"] <- round(newdata[1, "x"])

  if (length(draw_quantiles) > 0 & !scales::zero_range(range(data$y))) {
    stopifnot(all(draw_quantiles >= 0), all(draw_quantiles <=
      1))
    quantiles <- ggplot2:::create_quantile_segment_frame(data, draw_quantiles)
    aesthetics <- data[rep(1, nrow(quantiles)), setdiff(names(data), c("x", "y")), drop = FALSE]
    aesthetics$alpha <- rep(1, nrow(quantiles))
    both <- cbind(quantiles, aesthetics)
    quantile_grob <- GeomPath$draw_panel(both, ...)
    ggplot2:::ggname("geom_split_violin", grid::grobTree(GeomPolygon$draw_panel(newdata, ...), quantile_grob))
  }
  else {
    ggplot2:::ggname("geom_split_violin", GeomPolygon$draw_panel(newdata, ...))
  }
})

geom_split_violin <- function(mapping = NULL, data = NULL, stat = "ydensity", position = "identity", ..., 
                              draw_quantiles = NULL, trim = TRUE, scale = "area", na.rm = FALSE, 
                              show.legend = NA, inherit.aes = TRUE) {
  layer(data = data, mapping = mapping, stat = stat, geom = GeomSplitViolin, 
        position = position, show.legend = show.legend, inherit.aes = inherit.aes, 
        params = list(trim = trim, scale = scale, draw_quantiles = draw_quantiles, na.rm = na.rm, ...))
}
```

```{r}
splitvio <- subset(weather_clean_unique, select = c(Year, Air_Temp, Wind_Chill))
splitvio <- pivot_longer(splitvio, cols = c(Air_Temp, Wind_Chill), names_to = "Type", values_to = "Temp")
splitvio <- na.omit(splitvio)
max_values <- splitvio %>%
  filter(Type == "Air_Temp")%>%
  group_by(Year) %>%
  summarize(Temp = max(Temp))

min_values <- splitvio %>%
  group_by(Year, Type) %>%
  summarize(Temp = min(Temp))
```



```{r}
ggplot(splitvio,aes(x=Year, y=Temp,fill=Type))+
  geom_split_violin()+
  scale_fill_manual(values=c(Wind_Chill="dodgerblue3",Air_Temp="steelblue1"), labels = c(Wind_Chill="Wind Chill", Air_Temp = "Air Temperature"))+
  theme_classic()+
  geom_point(data=max_values, aes(x=Year, y=Temp, fill = NULL))+
  geom_point(data=min_values, aes(x=Year, y=Temp, color= Type), size = 3)+
  theme(legend.position = "none")+
  ylab("Temperature (°C)")+
  xlab("Year")+
  geom_hline(yintercept=10, linetype="dashed", size = 1.25)+
  theme(axis.text.y = element_text(size = 19,colour="black"))+ 
  theme(axis.text.x = element_text(size = 19,angle = 315, hjust=-.15 ,vjust = 1.25, colour="black"))+
  theme(axis.title = element_text(size = 25))
```

```{r}
weather_clean_unique <- weather_clean_unique %>%
mutate(
    month = as.numeric(format(Date, "%m")),
    year = as.numeric(format(Date, "%Y")),
    water_year = ifelse(month >= 10, year + 1, year) # October starts a new water year
  )
tot_rain <- weather_clean_unique %>%
  group_by(water_year) %>%
  summarize(tot_rain = sum(Rain))

tot_rain <- tot_rain %>% filter(water_year != c(2006))
tot_rain <- tot_rain %>% filter(water_year != c(2025))

tot_rain$water_year <- as.factor(tot_rain$water_year)
tot_rain$tot_rain <- tot_rain$tot_rain/10

el_nino <- c("la_nina", "no_enso", "el_nino", "la_nina", "la_nina","no_enso","no_enso","no_enso","el_nino", "no_enso","la_nina","no_enso","el_nino","no_enso","la_nina","la_nina","la_nina","el_nino")
tot_rain$el_nino <- el_nino
```

```{r}
ggplot(tot_rain, aes(x=water_year, y=tot_rain, fill = el_nino))+
  geom_bar(stat="identity")+
  scale_fill_manual(values=c(la_nina="#200192",no_enso="#4473c4", el_nino = "#009999"), labels = c(la_nina="La Niña", no_enso = "No ENSO", el_nino = "El Niño"))+
  theme_classic()+
   theme(axis.text.y = element_text(size = 18,colour="black"))+ 
  theme(axis.text.x = element_text(size = 18,angle = 315, hjust=-.15 ,vjust = 1.25, colour="black"))+
  theme(axis.title = element_text(size = 20))+
  theme(legend.title = element_text(size = 20))+
  theme(legend.text = element_text(size = 20))+
  labs(x = "Water Year", y = "Total Rainfall (cm)", fill= "ENSO")
  


```

```{r}
ggplot(weather_clean_unique, aes(x=Date, y=Air_Temp))+
  geom_point(size = 1, color= "#64bafb")+
  theme_classic()+
   theme(axis.text.y = element_text(size = 18,colour="black"))+ 
  theme(axis.text.x = element_text(size = 18,angle = 315, hjust=-.15 ,vjust = 1.25, colour="black"))+
  theme(axis.title = element_text(size = 20))+
  labs(x = "Date", y = "Air Temperature (°C)")+
  scale_x_datetime(date_breaks = "1 year", date_labels = "%Y")
  
```
```{r}
month_rain <- weather_clean_unique %>%
  group_by(water_year, month) %>%
  summarize(month_rain = sum(Rain))
month_rain$month <- factor(month_rain$month, levels=c("10", "11", "12", "1", "2", "3", "4", "5", "6", "7", "8", "9"))
month_rain$water_year <- as.factor(month_rain$water_year)
month_rain$month_rain <- month_rain$month_rain/10
month_rain <- subset(month_rain, !(water_year == "2008" & month == "10"))
month_rain <- subset(month_rain, !(water_year == "2010" & month == "06"))
month_rain <- subset(month_rain, !(water_year == "2006" | water_year == "2025"))



month_rain_max <- month_rain %>%
  group_by(water_year)%>%
  slice(which.max(month_rain))
month_rain_max$month <- factor(month_rain_max$month, levels=c("10", "11", "12", "1", "2", "3", "4", "5", "6", "7", "8", "9"))
month_rain_max$water_year <- as.factor(month_rain_max$water_year)

month_rain_min <- month_rain %>%
  group_by(water_year)%>%
  slice(which.min(month_rain))
month_rain_min$month <- factor(month_rain_min$month, levels=c("10", "11", "12", "1", "2", "3", "4", "5", "6", "7", "8", "9"))
month_rain_min$water_year <- as.factor(month_rain_min$water_year)



```

```{r}


level_order <- c("10", "11", "12", "1", "2", "3", "4", "5", "6", "7", "8", "9")
custom_labels <- c("Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep")

ggplot(month_rain, aes(x = month, y = month_rain, col = water_year, group = water_year)) +
  # Add shapes for max and min with specific mapping to shapes
  geom_point(data = month_rain_max, aes(shape = "Annual Maximum"), size = 3) +
  geom_point(data = month_rain_min, aes(shape = "Annual Minimum"), size = 3) +
  geom_line() +
  # Consolidate shape legend into a single scale
  scale_shape_manual(
    name = "Rainfall Markers",
    values = c("Annual Maximum" = 16, "Annual Minimum" = 17)  # Shapes for the legend
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(size = 18, colour = "black"),
    axis.text.x = element_text(size = 18, angle = 315, hjust = -0.15, vjust = 1.25, colour = "black"),
    axis.title = element_text(size = 20),
    legend.title = element_text(size = 20),
    legend.text = element_text(size = 20)
  ) +
  labs(
    x = "Month",
    y = "Monthly rainfall (cm)",
    color = "Water Year"
  ) +
  scale_x_discrete(
    limits = level_order,  # Keeps the original ordering
    labels = custom_labels # Assigns the custom labels
  )

```


